sudo: required
services:
  - docker
before_install:
  - docker build -t ajaypati/docker-react -f Dockerfile.dev .
script:
  - docker run ajaypati/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-us-east-1-703745605407"
  bucker_path: "docker"
  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secute:"$AWS_SECRET_KEY"








